- name: install mysql server
  ansible.builtin.dnf:
    name: mysql_server
    status: latest

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    status: started
    enabled: yes

# check already password is already created or setup or not.

- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"