- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

# check already password is already created or setup or not.

- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  register: mysql_connection_output