- name: install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

# check already password is already created or setup or not.

- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: yes
  register: mysql_connection_output

- name: print the output
  ansible.builtin.debug: 
    msg: "output: {{ mysql_connection_output }}"

# - name: setup the password
#   ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
#   when: mysql_connection_output.failed is true